### ISSUE TITLE
creating windows bilt.

### ISSUE THREAD

**Issue by yukie-nobuharu** [martinkirch/showergel#2]
hi. i'm new to github. i have a suggestion. can you create a windows equivlent to this? or, do something to run it in github. dvance thanks!

**Comment by martinkirch** [comment]
Hello,
In theory it's possible : Liquidsoap can be installed on Windows, and `pip install` works on Windows too. It would require a test to skip the `systemd` step during installation.
In practice, I don't have any machine running Windows... but any test feedback on this would be interesting !

**Comment by yukie-nobuharu** [comment]
o, it works. thanks!
